spring.application.name=hozzat

spring.datasource.url=jdbc:postgresql://localhost:5432/hozzat
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

ml.service.url=http://localhost:5000